pub struct Signal {
    pub signal_id: i64,
    vehicle_id: i64,
    trip_id: i64,
    time_stamp: i64,
    latitude: f64,
    longitude: f64,
    speed: Option<f64>,
    maf: Option<f64>,
    rpm: Option<f64>,
    abs_load: Option<f64>,
    oat: Option<f64>,
    fuel_rate: Option<f64>,
    ac_power_kw: Option<f64>,
    ac_power_w: Option<f64>,
    heater_power_w: Option<f64>,
    hv_bat_current: Option<f64>,
    hv_bat_soc: Option<f64>,
    hv_bat_volt: Option<f64>,
    st_ftb_1: Option<f64>,
    st_ftb_2: Option<f64>,
    lt_ftb_1: Option<f64>,
    lt_ftb_2: Option<f64>,
    elevation: Option<f64>,
    elevation_smooth: Option<f64>,
    gradient: Option<f64>,
    energy_consumption: Option<f64>,
    match_latitude: f64,
    match_longitude: f64,
    match_type: i64,
    speed_limit_type: Option<i64>,
    speed_limit: Option<String>,
    speed_limit_direct: Option<i64>,
    intersection: Option<i64>,
    bus_stop: Option<i64>,
    focus_points: Option<String>,
    h3_12: Option<i64>,
}
